---

version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"

formats: all

python:
  install:
    - path: .
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

...
